name: flutter_gl_web
description: Web platform implementation of flutter_gl
homepage: https://github.com
version: 0.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterGlPlugin
        fileName: flutter_gl_web.dart

dependencies:  
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_gl_platform_interface:
    path: ../flutter_gl_platform_interface
 
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"
